services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: userdb-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: myapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - user-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis Cache
  redis:
    image: gazal94/redis:7-alpine
    container_name: userdb-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis123
    environment:
      REDIS_PASSWORD: redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - user-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Backend API (builds from current source)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: userdb-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/myapp?authSource=admin
      REDIS_URL: redis://:redis123@redis:6379
    ports:
      - "5000:5000"
    networks:
      - user-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend (builds from current source)
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    container_name: userdb-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - user-network
    depends_on:
      backend:
        condition: service_healthy

volumes:
  mongodb_data:
  redis_data:

networks:
  user-network:
    driver: bridge
